require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
      
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
